using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace DAL.Model
{
    public class Users
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // // external Id, easier to reference: 1,2,3 or A, B, C etc.
        // public string Id { get; set; }                          

        // public string Body { get; set; } = string.Empty;

        // [BsonDateTimeOptions]
        // public DateTime UpdatedOn { get; set; } = DateTime.Now;

        // public NoteImage HeaderImage { get; set; }

        // public int UserId { get; set; } = 0;

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int Role { get; set; }
    }
}
